### ISSUE TITLE
I cannot build on Windows ...

### ISSUE THREAD

**Issue by sjk7** [tsoding/musializer#73] opened 2024-01-23 15:58 UTC
... Probably because I am too stupid to work nob.exe, but here's what happens when I try:
 ----------------------------------------------------------------------------------------------------

Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd /d c:\users\DEVNVME\Desktop\musializer

c:\Users\DevNVME\Desktop\musializer>"C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build/vcvarsall.bat" x86_amd64
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.8.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'

c:\Users\DevNVME\Desktop\musializer>cl.exe nob.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nob.c
Microsoft (R) Incremental Linker Version 14.38.33133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nob.exe
nob.obj

c:\Users\DevNVME\Desktop\musializer>nob.exe
[INFO] --- STAGE 1 ---
[INFO] created directory `build`
[INFO] Generating ./build/config.h
[INFO] CMD: cl.exe nob.c -DCONFIGURED
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nob.c
Microsoft (R) Incremental Linker Version 14.38.33133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nob.exe
nob.obj
LINK : fatal error LNK1104: cannot open file 'nob.exe'
[ERROR] command exited with exit code 2

**Comment by rexim** [comment] 2024-02-08 00:15
Duplicate of #62

**Closed as completed by rexim** 2024-02-08 00:15 UTC
