### ISSUE TITLE
[macOS] No sound on Mac

### ISSUE THREAD

**Issue by nicolasdanelon** [tsoding/musializer#49] opened 2023-10-24 11:06 UTC
Running macOS Sonoma 14.0 on a MacBook Air M1, graph works but no audio =/

### Logs when compiling

```bash
./nob
[INFO] created directory `build`
[INFO] Saving configuration to ./build/build.conf
[INFO] ------------------------------
[INFO] Target: macos
[INFO] Hotreload: DISABLED
[INFO] Microphone: DISABLED
[INFO] ------------------------------
[INFO] created directory `./build/raylib`
[INFO] created directory `./build/raylib/macos`
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/rcore.c -o ./build/raylib/macos/rcore.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/raudio.c -o ./build/raylib/macos/raudio.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -x objective-c -c ./raylib/raylib-4.5.0/src/rglfw.c -o ./build/raylib/macos/rglfw.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/rmodels.c -o ./build/raylib/macos/rmodels.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/rshapes.c -o ./build/raylib/macos/rshapes.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/rtext.c -o ./build/raylib/macos/rtext.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/rtextures.c -o ./build/raylib/macos/rtextures.o
[INFO] CMD: clang -g -DPLATFORM_DESKTOP -fPIC -I./raylib/raylib-4.5.0/src/external/glfw/include -Iexternal/glfw/deps/ming -DGRAPHICS_API_OPENGL_33 -c ./raylib/raylib-4.5.0/src/utils.c -o ./build/raylib/macos/utils.o
In file included from ./raylib/raylib-4.5.0/src/rmodels.c:112:
./raylib/raylib-4.5.0/src/external/par_shapes.h:1133:32: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-const-int-float-conversion]
 1133 |     float r = (float) rand() / RAND_MAX;
      |                              ~ ^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/stdlib.h:105:18: note: expanded from macro 'RAND_MAX'
  105 | #define RAND_MAX        0x7fffffff
      |                         ^~~~~~~~~~
./raylib/raylib-4.5.0/src/raudio.c:1297:45: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
 1297 |         qoaplay_desc *ctxQoa = qoaplay_open(fileName);
      |                                             ^~~~~~~~
./raylib/raylib-4.5.0/src/external/qoaplay.c:86:34: note: passing argument to parameter 'path' here
   86 | qoaplay_desc *qoaplay_open(char *path)
      |                                  ^
1 warning generated.
1 warning generated.
[INFO] CMD: ar -crs ./build/raylib/macos/libraylib.a ./build/raylib/macos/rcore.o ./build/raylib/macos/raudio.o ./build/raylib/macos/rglfw.o ./build/raylib/macos/rmodels.o ./build/raylib/macos/rshapes.o ./build/raylib/macos/rtext.o ./build/raylib/macos/rtextures.o ./build/raylib/macos/utils.o
[INFO] CMD: clang -Wall -Wextra -g -I./raylib/raylib-4.5.0/src/ -o ./build/musializer ./src/plug.c ./src/ffmpeg_linux.c ./src/musializer.c ./build/raylib/macos/libraylib.a -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL -lm -ldl -lpthread
[INFO] created directory `./build/resources/`
[INFO] created directory `./build/resources//logo`
[INFO] copying ./resources//logo/logo-256.ico -> ./build/resources//logo/logo-256.ico
[INFO] copying ./resources//logo/logo-256.png -> ./build/resources//logo/logo-256.png
[INFO] copying ./resources//logo/logo.svg -> ./build/resources//logo/logo.svg
[INFO] created directory `./build/resources//icons`
[INFO] copying ./resources//icons/fullscreen.svg -> ./build/resources//icons/fullscreen.svg
[INFO] copying ./resources//icons/volume.png -> ./build/resources//icons/volume.png
[INFO] copying ./resources//icons/volume.svg -> ./build/resources//icons/volume.svg
[INFO] copying ./resources//icons/fullscreen.png -> ./build/resources//icons/fullscreen.png
[INFO] created directory `./build/resources//shaders`
[INFO] created directory `./build/resources//shaders/glsl120`
[INFO] copying ./resources//shaders/glsl120/circle.fs -> ./build/resources//shaders/glsl120/circle.fs
[INFO] created directory `./build/resources//shaders/glsl330`
[INFO] copying ./resources//shaders/glsl330/circle.fs -> ./build/resources//shaders/glsl330/circle.fs
[INFO] created directory `./build/resources//fonts`
[INFO] copying ./resources//fonts/OFL.txt -> ./build/resources//fonts/OFL.txt
[INFO] copying ./resources//fonts/Alegreya-Regular.ttf -> ./build/resources//fonts/Alegreya-Regular.ttf

```

### Logs when running

```bash
./build/musializer
INFO: FILEIO: [./resources/logo/logo-256.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (256x256 | R8G8B8A8 | 1 mipmaps)
INFO: Initializing raylib 4.5
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1440 x 900
INFO:     > Screen size:  1280 x 720
INFO:     > Render size:  1280 x 720
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 43
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M1
INFO:     > Version:  4.1 Metal - 86
INFO:     > GLSL:     4.10
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
WARNING: GLFW: Error: 65548 Description: Cocoa: Regular windows do not have icons on macOS
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / Null
INFO:     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   48000 -> 48000
INFO:     > Periods size:  1440
INFO: FILEIO: [./resources/fonts/Alegreya-Regular.ttf] File loaded successfully
INFO: TEXTURE: [ID 3] Texture loaded successfully (1024x1024 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Data loaded successfully (64 pixel size | 95 glyphs)
INFO: TEXTURE: [ID 3] Mipmaps generated automatically, total: 11
INFO: FILEIO: [./resources/shaders/glsl330/circle.fs] Text file loaded successfully
INFO: SHADER: [ID 4] Fragment shader compiled successfully
INFO: SHADER: [ID 5] Program shader loaded successfully
INFO: SHADER: [ID 5] Shader attribute (vertexPosition) set at location: 0
INFO: SHADER: [ID 5] Shader attribute (vertexTexCoord) set at location: 1
WARNING: SHADER: [ID 5] Failed to find shader attribute: vertexTexCoord2
WARNING: SHADER: [ID 5] Failed to find shader attribute: vertexNormal
WARNING: SHADER: [ID 5] Failed to find shader attribute: vertexTangent
INFO: SHADER: [ID 5] Shader attribute (vertexColor) set at location: 3
INFO: SHADER: [ID 5] Shader uniform (mvp) set at location: 0
WARNING: SHADER: [ID 5] Failed to find shader uniform: matView
WARNING: SHADER: [ID 5] Failed to find shader uniform: matProjection
WARNING: SHADER: [ID 5] Failed to find shader uniform: matModel
WARNING: SHADER: [ID 5] Failed to find shader uniform: matNormal
WARNING: SHADER: [ID 5] Failed to find shader uniform: colDiffuse
WARNING: SHADER: [ID 5] Failed to find shader uniform: texture0
WARNING: SHADER: [ID 5] Failed to find shader uniform: texture1
WARNING: SHADER: [ID 5] Failed to find shader uniform: texture2
INFO: SHADER: [ID 5] Shader uniform (radius) set at location: 4
INFO: SHADER: [ID 5] Shader uniform (power) set at location: 5
INFO: TEXTURE: [ID 4] Texture loaded successfully (1600x900 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Depth renderbuffer loaded successfully (32 bits)
INFO: FBO: [ID 1] Framebuffer object created successfully
INFO: STREAM: Initialized successfully (44100 Hz, 16 bit, Stereo)
INFO: FILEIO: [/Users/ihavenoideawhatimdoing/Movies/nu11 wip works 2016-2022 (ogg)/fading away (2022)/fading away.ogg] Music file loaded successfully
INFO:     > Sample rate:   44100 Hz
INFO:     > Sample size:   16 bits
INFO:     > Channels:      2 (Stereo)
INFO:     > Total frames:  3466969
INFO: FILEIO: [./resources/icons/fullscreen.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (2048x512 | GRAY_ALPHA | 1 mipmaps)
INFO: TEXTURE: [ID 5] Texture loaded successfully (2048x512 | GRAY_ALPHA | 1 mipmaps)
INFO: TEXTURE: [ID 5] Mipmaps generated automatically, total: 12
INFO: FILEIO: [./resources/icons/volume.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (1536x512 | GRAY_ALPHA | 1 mipmaps)
INFO: TEXTURE: [ID 6] Texture loaded successfully (1536x512 | GRAY_ALPHA | 1 mipmaps)
INFO: TEXTURE: [ID 6] Mipmaps generated automatically, total: 11
```

Funny thing: When I render a video the output.mp4 has audio (yeah... ffmpeg 6.0_1 is working), when I run the songs from musializar binary I have no sound :/

**Comment by rexim** [comment] 2023-10-25 23:09
I feel like this is duplicate of #35

**Closed as completed** 2023-10-26 07:53 UTC
